import { debug } from '@/utils/logging';
import {} from '@/api/Foods/foodService.ts';
import type { Food, FoodVariant } from '@/types/food';
import {
  NutritionixItem,
  OpenFoodFactsProduct,
} from '@/components/FoodSearch/FoodSearch';
import { FatSecretFoodItem } from '@/api/Foods/fatSecret';

export const convertOpenFoodFactsToFood = (
  product: OpenFoodFactsProduct,
  autoScaleOpenFoodFactsImports: boolean
): Food => {
  // Calculate scaling factor based on serving_quantity (defaults to 100g if not provided)
  // Only apply scaling if autoScaleOpenFoodFactsImports preference is enabled
  const shouldScale =
    autoScaleOpenFoodFactsImports &&
    product.serving_quantity &&
    product.serving_quantity > 0;
  const servingSize = shouldScale ? product.serving_quantity! : 100;
  const scaleFactor = shouldScale ? servingSize / 100 : 1; // Scale from 100g to actual serving size, or 1 if disabled

  const defaultVariant: FoodVariant = {
    id: 'default', // Assign a default ID for now
    serving_size: servingSize,
    serving_unit: 'g',
    calories: Math.round(
      (product.nutriments['energy-kcal_100g'] || 0) * scaleFactor
    ), // Assumed to be in kcal, and scaled from 100g to serving
    protein:
      Math.round(
        (product.nutriments['proteins_100g'] || 0) * scaleFactor * 10
      ) / 10,
    carbs:
      Math.round(
        (product.nutriments['carbohydrates_100g'] || 0) * scaleFactor * 10
      ) / 10,
    fat:
      Math.round((product.nutriments['fat_100g'] || 0) * scaleFactor * 10) / 10,
    saturated_fat:
      Math.round(
        (product.nutriments['saturated-fat_100g'] || 0) * scaleFactor * 10
      ) / 10,
    sodium: product.nutriments['sodium_100g']
      ? Math.round(product.nutriments['sodium_100g'] * 1000 * scaleFactor)
      : 0,
    dietary_fiber:
      Math.round((product.nutriments['fiber_100g'] || 0) * scaleFactor * 10) /
      10,
    sugars:
      Math.round((product.nutriments['sugars_100g'] || 0) * scaleFactor * 10) /
      10,
    // Initialize other nutrients to 0 or appropriate defaults
    polyunsaturated_fat: 0,
    monounsaturated_fat: 0,
    trans_fat: 0,
    cholesterol: 0,
    potassium: 0,
    vitamin_a: 0,
    vitamin_c: 0,
    calcium: 0,
    iron: 0,
    is_default: true,
    is_locked: shouldScale, // Enable auto-scale only if preference is enabled and scaling was applied
    glycemic_index: 'None', // Default GI for OpenFoodFacts
  };

  const convertedFood: Food = {
    id: undefined, // ID will be generated by the backend
    name: product.product_name,
    brand: product.brands?.split(',')[0]?.trim() || '',
    is_custom: false,
    provider_external_id: product.code,
    provider_type: 'openfoodfacts',
    default_variant: defaultVariant,
    variants: [defaultVariant],
    glycemic_index: 'None', // Default GI for OpenFoodFacts
  };
  return convertedFood;
};

export const formatUsdaNutrientsForDisplay = (
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  usdaItem: any,
  loggingLevel: string
): Partial<FoodVariant> => {
  const nutrients: Partial<FoodVariant> = {
    calories: 0,
    protein: 0,
    carbs: 0,
    fat: 0,
    saturated_fat: 0,
    polyunsaturated_fat: 0,
    monounsaturated_fat: 0,
    trans_fat: 0,
    cholesterol: 0,
    sodium: 0,
    potassium: 0,
    dietary_fiber: 0,
    sugars: 0,
    vitamin_a: 0,
    vitamin_c: 0,
    calcium: 0,
    iron: 0,
    glycemic_index: 'None',
  };

  if (usdaItem.foodNutrients) {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    usdaItem.foodNutrients.forEach((nutrient: any) => {
      const nutrientName = nutrient.nutrientName.toLowerCase();
      const value = nutrient.value;
      const unitName = nutrient.unitName?.toLowerCase() || '';

      debug(
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        loggingLevel as any,
        `Processing USDA nutrient: ${nutrient.nutrientName} (value: ${value}, unit: ${nutrient.unitName})`
      );

      if (
        nutrientName.includes('energy') &&
        (unitName === 'kcal' ||
          unitName === 'calorie' ||
          nutrientName.includes('kcal'))
      ) {
        nutrients.calories = value;
      } else if (nutrientName === 'protein') {
        nutrients.protein = value;
      } else if (
        nutrientName.includes('carbohydrate, total') ||
        nutrientName.includes('carbohydrate')
      ) {
        nutrients.carbs = value;
      } else if (
        nutrientName.includes('total lipid (fat)') ||
        nutrientName.includes('fat, total') ||
        nutrientName.includes('fat')
      ) {
        nutrients.fat = value;
      } else if (
        nutrientName.includes('fatty acids, total saturated') ||
        nutrientName.includes('saturated fat')
      ) {
        nutrients.saturated_fat = value;
      } else if (nutrientName.includes('polyunsaturated fat')) {
        nutrients.polyunsaturated_fat = value;
      } else if (nutrientName.includes('monounsaturated fat')) {
        nutrients.monounsaturated_fat = value;
      } else if (nutrientName.includes('trans fat')) {
        nutrients.trans_fat = value;
      } else if (nutrientName.includes('cholesterol')) {
        nutrients.cholesterol = value;
      } else if (
        nutrientName.includes('sodium, na') ||
        nutrientName.includes('sodium')
      ) {
        nutrients.sodium = value;
      } else if (
        nutrientName.includes('potassium, k') ||
        nutrientName.includes('potassium')
      ) {
        nutrients.potassium = value;
      } else if (
        nutrientName.includes('fiber, total dietary') ||
        nutrientName.includes('fiber')
      ) {
        nutrients.dietary_fiber = value;
      } else if (
        nutrientName.includes('sugars, total') ||
        nutrientName.includes('sugars')
      ) {
        nutrients.sugars = value;
      } else if (nutrientName.includes('vitamin a')) {
        nutrients.vitamin_a = value;
      } else if (nutrientName.includes('vitamin c')) {
        nutrients.vitamin_c = value;
      } else if (
        nutrientName.includes('calcium, ca') ||
        nutrientName.includes('calcium')
      ) {
        nutrients.calcium = value;
      } else if (
        nutrientName.includes('iron, fe') ||
        nutrientName.includes('iron')
      ) {
        nutrients.iron = value;
      }
    });
  }
  return nutrients;
};

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const convertUsdaToFood = (item: any, nutrientData: any): Food => {
  const defaultVariant: FoodVariant = {
    id: 'default', // Assign a default ID for now
    serving_size: nutrientData.servingSize,
    serving_unit: nutrientData.servingSizeUnit,
    calories: nutrientData.calories, // Assumed to be in kcal
    protein: nutrientData.protein,
    carbs: nutrientData.carbohydrates,
    fat: nutrientData.fat,
    saturated_fat: nutrientData.saturatedFat || 0,
    polyunsaturated_fat: nutrientData.polyunsaturatedFat || 0,
    monounsaturated_fat: nutrientData.monounsaturatedFat || 0,
    trans_fat: nutrientData.transFat || 0,
    cholesterol: nutrientData.cholesterol || 0,
    sodium: nutrientData.sodium || 0,
    potassium: nutrientData.potassium || 0,
    dietary_fiber: nutrientData.fiber || 0,
    sugars: nutrientData.sugars || 0,
    vitamin_a: nutrientData.vitaminA || 0,
    vitamin_c: nutrientData.vitaminC || 0,
    calcium: nutrientData.calcium || 0,
    iron: nutrientData.iron || 0,
    is_default: true,
    glycemic_index: 'None', // USDA API does not provide GI directly
  };

  return {
    id: undefined, // ID will be generated by the backend
    name: nutrientData.description,
    brand: nutrientData.brandOwner || null,
    is_custom: false,
    provider_external_id: item.fdcId.toString(),
    provider_type: 'usda',
    default_variant: defaultVariant,
    variants: [defaultVariant],
    glycemic_index: 'None',
  };
};

export const convertNutritionixToFood = (
  item: NutritionixItem,
  nutrientData?: NutritionixItem
): Food => {
  const source = nutrientData || item;

  const defaultVariant: FoodVariant = {
    id: 'default',
    serving_size: item.serving_size || 0,
    serving_unit: item.serving_unit || 'unit',
    calories: source.calories || 0,
    protein: source.protein || 0,
    carbs: source.carbs || 0,
    fat: source.fat || 0,
    saturated_fat: source.saturated_fat || 0,
    polyunsaturated_fat: source.polyunsaturated_fat || 0,
    monounsaturated_fat: source.monounsaturated_fat || 0,
    trans_fat: source.trans_fat || 0,
    cholesterol: source.cholesterol || 0,
    sodium: source.sodium || 0,
    potassium: source.potassium || 0,
    dietary_fiber: source.dietary_fiber || 0,
    sugars: source.sugars || 0,
    vitamin_a: source.vitamin_a || 0,
    vitamin_c: source.vitamin_c || 0,
    calcium: source.calcium || 0,
    iron: source.iron || 0,
    is_default: true,
    glycemic_index: source.glycemic_index || 'None',
  };

  return {
    id: undefined,
    name: source.food_name || source.name || 'Unknown',
    brand: source.brand_name || source.brand,
    is_custom: false,
    provider_external_id: item.id,
    provider_type: 'nutritionix',
    default_variant: defaultVariant,
    variants: [defaultVariant],
    glycemic_index: source.glycemic_index || 'None',
  };
};

export const convertFatSecretToFood = (
  item: FatSecretFoodItem,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  nutrientData: any
): Food => {
  const defaultVariant: FoodVariant = {
    id: 'default', // Assign a default ID for now
    serving_size: nutrientData.serving_qty,
    serving_unit: nutrientData.serving_unit,
    calories: nutrientData.calories, // Assumed to be in kcal
    protein: nutrientData.protein,
    carbs: nutrientData.carbohydrates,
    fat: nutrientData.fat,
    saturated_fat: nutrientData.saturated_fat,
    polyunsaturated_fat: nutrientData.polyunsaturated_fat || 0,
    monounsaturated_fat: nutrientData.monounsaturated_fat || 0,
    trans_fat: nutrientData.trans_fat || 0,
    cholesterol: nutrientData.cholesterol || 0,
    sodium: nutrientData.sodium,
    potassium: nutrientData.potassium || 0,
    dietary_fiber: nutrientData.dietary_fiber || 0,
    sugars: nutrientData.sugars || 0,
    vitamin_a: nutrientData.vitamin_a || 0,
    vitamin_c: nutrientData.vitamin_c || 0,
    calcium: nutrientData.calcium || 0,
    iron: nutrientData.iron || 0,
    is_default: true,
    glycemic_index: nutrientData.glycemic_index || 'None',
  };

  return {
    id: undefined, // ID will be generated by the backend
    name: nutrientData.name,
    brand: nutrientData.brand || item.brand_name || null, // Use detailed brand if available, else from search
    is_custom: false,
    provider_external_id: item.food_id, // Use food_id from FatSecretFoodItem
    provider_type: 'fatsecret',
    default_variant: defaultVariant,
    variants: [defaultVariant],
    glycemic_index: nutrientData.glycemic_index || 'None',
  };
};
